export const allConstants = {

    ADD_PLAYER_REQUEST: 'ADD_PLAYER_REQUEST',
    ADD_PLAYER_SUCCESS: 'ADD_PLAYER_SUCCESS',
    ADD_PLAYER_FAILURE: 'ADD_PLAYER_FAILURE',

    VIEW_ALL_PLAYERS_REQUEST: 'VIEW_ALL_PLAYERS_REQUEST',
    VIEW_ALL_PLAYERS_SUCCESS: 'VIEW_ALL_PLAYERS_SUCCESS',
    VIEW_ALL_PLAYERS_FAILURE: 'VIEW_ALL_PLAYERS_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'

}